### PR TITLE
new profile scheme

### PR DESCRIPTION
**Pull request by renegart**
Hi, I've restructured the profile scheme to integrate the experimental 17.1 profiles for amd64 systems.
I've tested it on two of my systems and it seems to work.
But I don't want to merge them to the master without review/discusion.

The user has to reset his profile before he can continue.

I've also updated 'unity-base/unity-build-env' package to set the links correctly
There are also some changes in the 'profile.bashrc' to distinguish between stable/development and experimental profiles.

The ehooks seems also to work. I've testet it with firefox build, but it should also be re-tested

### CODE REVIEW

**Comment by shiznix** [comment]
Only unknown is the experimental 17.1 profile which is still a work in progress.

Having a read of https://www.gentoo.org/support/news-items/2017-12-26-experimental-amd64-17-1-profiles.html it looks unreasonably fragile to force onto users at this early stage.

The overlay recommends installation over a stable system and that may give users a false sense of stability to then find their system breaking because they haven't followed the profile migration steps.
(Still get twitches when I think of the recent system break Gentoo caused for overlays moving lib32 around in stable 13.0 profile).

Everything else looks fine including profile restructure, but hold off on switching to 17.1 just yet.

**Comment by c4pp4** [comment]
Basically I have no problem with it. Why not to have 'no symlink' choice and it's good to be ready for upcoming changes. But this is very thin ice, so beware. I'm not sure they know what they are doing: https://github.com/gentoo/gentoo/commit/f6826ec92984881f36f3f19018849cf50fa20ce4

I think there should be very detailed walkthrough for the transition. Not like this: https://www.gentoo.org/support/news-items/2017-12-26-experimental-amd64-17-1-profiles.html
Citation: "Reboot your system and see if it still boots."
It sounds like good joke, not like serious procedure.

I think there should be only one directory for every release, this is not much efficient:
profiles/linux/amd64/17.0/zesty
profiles/linux/amd64/17.1/zesty
profiles/linux/x86/17.0/zesty
profiles/releases/zesty

I will look at it deeply later if you don't mind. :)

**Comment by shiznix** [comment]
I missed the 'UNITY_EXPERIMENTAL_[artful|zesty]=yes' variable that needed to be set.
Seems fair to commit as it's well masked to protect the user.

A couple of changes:
Change 'UNITY_EXPERIMENTAL_' to 'UNITY_EXPERIMENTAL_PROFILE_' so it doesn't get confused with 'UNITY_DEVELOPMENT_'
Include the https://www.gentoo.org/support/news-items/2017-12-26-experimental-amd64-17-1-profiles.html link in the die message to get users in the right direction on what kind of breakage they can expect.

**Comment by renegart** [comment]
Done. Pull request is updated to current master branch and the two suggestions are incorporated.

**Comment by c4pp4** [comment]
@renegart: Just to be clear - compare how many steps you have to do when adding/removing release when there is only one directory (old fashioned way) and when it's divided according to your suggestion. I think the new way is more error-prone. I'm not the one who is doing that kind of commit (adding/removing release) so if shiznix is ok with it, forget my note. :)

**Comment by shiznix** [comment]
I can appreciate the efficiency concern with the new restructure but it really doesn't greatly affect the workflow in bumping to a newer version.

What's most important is that ehooks and unity-portage.p* files are all located in one directory per release and that's been taken care of.

Unless you guys have any more concerns I'd say go ahead and commit :)

**Pull request merged**
